2.1
Sergey-Pravdyukov/Homeworks pull request #25
Opened 2016-10-27 18:03 UTC by Sergey-Pravdyukov

2016-11-04 17:58 UTC, jzuken requested changes

2016-11-04 17:58 UTC, jzuken commented on term3/hw2/1/computer.h
> +    bool wasInfected = false;
паблик поля?

2016-11-04 17:58 UTC, jzuken commented on term3/hw2/1/net.h
> +    Net(std::vector <Computer*>, std::vector <std::vector<Computer*> >);
а что, имена параметров писать уже не модно?

2016-11-04 17:58 UTC, jzuken commented on term3/hw2/1/net.h
> +    bool haveUninfectedComputers = true;
опять же паблик поля, ужас

2016-11-04 17:58 UTC, jzuken commented on term3/hw2/1/testvirus.cpp
> +    const int index = net->getComputerIndex(computer);
в Virus::getUninfectedComputer() этот код полностью повторяется. ничего с этим нельзя сделать?

2016-11-04 17:58 UTC, jzuken commented on term3/hw2/1/operationsystem.h
> +    const double LinuxInfectionProbability = 0.7;
стайлгайд уже отменили?

2016-11-04 19:53 UTC, Sergey-Pravdyukov commented on term3/hw2/1/net.h
> +    Net(std::vector <Computer*>, std::vector <std::vector<Computer*> >);
Это плохая практика вообще или в конкретном случае?

2016-11-05 15:44 UTC, jzuken commented on term3/hw2/1/net.h
> +    Net(std::vector <Computer*>, std::vector <std::vector<Computer*> >);
плохая практика

2016-11-07 20:15 UTC, merged